
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mio.cliente.boxworld.compiler.parser;

import com.mio.cliente.boxworld.compiler.lexer.MovesLexer;
import com.mio.cliente.boxworld.compiler.parser.MovesParserSym;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class MovesParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return MovesParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public MovesParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public MovesParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public MovesParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\031\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\003\000\002\004\007" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\012\003\000\002\006\005\000\002" +
    "\006\005\000\002\006\003\000\002\007\005\000\002\007" +
    "\005\000\002\007\004\000\002\007\003\000\002\010\005" +
    "\000\002\010\003\000\002\011\006\000\002\011\003\000" +
    "\002\011\003\000\002\013\003\000\002\013\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\052\000\014\015\010\016\004\017\014\020\012\021" +
    "\011\001\002\000\004\010\ufffa\001\002\000\004\010\020" +
    "\001\002\000\016\002\016\015\010\016\004\017\014\020" +
    "\012\021\011\001\002\000\016\002\ufffd\015\ufffd\016\ufffd" +
    "\017\ufffd\020\ufffd\021\ufffd\001\002\000\004\010\ufffb\001" +
    "\002\000\012\015\010\016\004\017\014\020\012\001\002" +
    "\000\004\010\ufff8\001\002\000\016\002\uffff\015\uffff\016" +
    "\uffff\017\uffff\020\uffff\021\uffff\001\002\000\004\010\ufff9" +
    "\001\002\000\016\002\ufffe\015\ufffe\016\ufffe\017\ufffe\020" +
    "\ufffe\021\ufffe\001\002\000\004\002\001\001\002\000\016" +
    "\002\000\015\000\016\000\017\000\020\000\021\000\001" +
    "\002\000\016\005\034\010\033\013\024\014\021\022\022" +
    "\023\032\001\002\000\014\004\uffeb\005\uffeb\006\uffeb\007" +
    "\uffeb\011\uffeb\001\002\000\004\010\uffea\001\002\000\004" +
    "\010\052\001\002\000\014\004\uffec\005\uffec\006\uffec\007" +
    "\uffec\011\uffec\001\002\000\004\011\050\001\002\000\014" +
    "\004\uffee\005\uffee\006\uffee\007\uffee\011\uffee\001\002\000" +
    "\014\004\ufff0\005\ufff0\006\ufff0\007\ufff0\011\ufff0\001\002" +
    "\000\014\004\ufff4\005\ufff4\006\043\007\044\011\ufff4\001" +
    "\002\000\010\004\041\005\040\011\ufff7\001\002\000\004" +
    "\010\uffe9\001\002\000\012\013\024\014\021\022\022\023" +
    "\032\001\002\000\014\010\033\013\024\014\021\022\022" +
    "\023\032\001\002\000\014\004\ufff1\005\ufff1\006\ufff1\007" +
    "\ufff1\011\ufff1\001\002\000\004\011\037\001\002\000\014" +
    "\004\uffef\005\uffef\006\uffef\007\uffef\011\uffef\001\002\000" +
    "\016\005\034\010\033\013\024\014\021\022\022\023\032" +
    "\001\002\000\016\005\034\010\033\013\024\014\021\022" +
    "\022\023\032\001\002\000\014\004\ufff6\005\ufff6\006\043" +
    "\007\044\011\ufff6\001\002\000\014\010\033\013\024\014" +
    "\021\022\022\023\032\001\002\000\014\010\033\013\024" +
    "\014\021\022\022\023\032\001\002\000\014\004\ufff2\005" +
    "\ufff2\006\ufff2\007\ufff2\011\ufff2\001\002\000\014\004\ufff3" +
    "\005\ufff3\006\ufff3\007\ufff3\011\ufff3\001\002\000\014\004" +
    "\ufff5\005\ufff5\006\043\007\044\011\ufff5\001\002\000\004" +
    "\012\051\001\002\000\016\002\ufffc\015\ufffc\016\ufffc\017" +
    "\ufffc\020\ufffc\021\ufffc\001\002\000\016\005\034\010\033" +
    "\013\024\014\021\022\022\023\032\001\002\000\010\004" +
    "\041\005\040\011\054\001\002\000\014\004\uffed\005\uffed" +
    "\006\uffed\007\uffed\011\uffed\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\052\000\012\002\005\003\012\004\006\005\004\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\003\016" +
    "\004\006\005\004\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\004\014\005\004\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\006\030\007\027" +
    "\010\026\011\025\012\024\013\022\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\011\035\013\022\001\001\000\010\010\034\011\025\013" +
    "\022\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\007\046\010\026\011\025\013\022\001" +
    "\001\000\012\007\041\010\026\011\025\013\022\001\001" +
    "\000\002\001\001\000\010\010\045\011\025\013\022\001" +
    "\001\000\010\010\044\011\025\013\022\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\006\052\007\027\010\026" +
    "\011\025\013\022\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MovesParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MovesParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MovesParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public MovesParser(MovesLexer lexer){
        super(lexer);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$MovesParser$actions {
  private final MovesParser parser;

  /** Constructor */
  CUP$MovesParser$actions(MovesParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$MovesParser$do_action_part00000000(
    int                        CUP$MovesParser$act_num,
    java_cup.runtime.lr_parser CUP$MovesParser$parser,
    java.util.Stack            CUP$MovesParser$stack,
    int                        CUP$MovesParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MovesParser$result;

      /* select the action based on the action number */
      switch (CUP$MovesParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= main EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-1)).value;
		RESULT = start_val;
              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-1)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$MovesParser$parser.done_parsing();
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // main ::= main movProd 
            {
              Object RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("main",0, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-1)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // main ::= movProd 
            {
              Object RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("main",0, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // movProd ::= PUSH dirProd 
            {
              Object RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("movProd",1, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-1)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // movProd ::= dirProd 
            {
              Object RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("movProd",1, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // dirProd ::= direccion PARENTESIS_A numero PARENTESIS_C PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("dirProd",2, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-4)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // direccion ::= RIGHT 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("direccion",3, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // direccion ::= LEFT 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("direccion",3, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // direccion ::= UP 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("direccion",3, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // direccion ::= DOWN 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("direccion",3, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // numero ::= a 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("numero",8, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // a ::= a SUMA b 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("a",4, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-2)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // a ::= a RESTA b 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("a",4, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-2)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // a ::= b 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("a",4, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // b ::= b MULTIPLICACION c 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("b",5, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-2)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // b ::= b DIVISION c 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("b",5, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-2)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // b ::= RESTA c 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("b",5, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-1)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // b ::= c 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("b",5, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // c ::= PARENTESIS_A d PARENTESIS_C 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("c",6, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-2)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // c ::= d 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("c",6, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // d ::= funcion PARENTESIS_A a PARENTESIS_C 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("d",7, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.elementAt(CUP$MovesParser$top-3)), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // d ::= ENTERO 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("d",7, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // d ::= DECIMAL 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("d",7, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // funcion ::= FLOOR 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("funcion",9, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // funcion ::= CEIL 
            {
              Integer RESULT =null;

              CUP$MovesParser$result = parser.getSymbolFactory().newSymbol("funcion",9, ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MovesParser$stack.peek()), RESULT);
            }
          return CUP$MovesParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$MovesParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$MovesParser$do_action(
    int                        CUP$MovesParser$act_num,
    java_cup.runtime.lr_parser CUP$MovesParser$parser,
    java.util.Stack            CUP$MovesParser$stack,
    int                        CUP$MovesParser$top)
    throws java.lang.Exception
    {
              return CUP$MovesParser$do_action_part00000000(
                               CUP$MovesParser$act_num,
                               CUP$MovesParser$parser,
                               CUP$MovesParser$stack,
                               CUP$MovesParser$top);
    }
}

}
