
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mio.cliente.boxworld.compiler.parser;

/** CUP generated class containing symbol constants. */
public class MovesParserSym {
  /* terminals */
  public static final int MULTIPLICACION = 4;
  public static final int DECIMAL = 10;
  public static final int DIVISION = 5;
  public static final int SUMA = 2;
  public static final int UP = 13;
  public static final int FLOOR = 16;
  public static final int CEIL = 17;
  public static final int RIGHT = 11;
  public static final int LEFT = 12;
  public static final int SYM = 18;
  public static final int EOF = 0;
  public static final int PUSH = 15;
  public static final int PARENTESIS_C = 7;
  public static final int error = 1;
  public static final int PARENTESIS_A = 6;
  public static final int DOWN = 14;
  public static final int PUNTO_COMA = 8;
  public static final int ENTERO = 9;
  public static final int RESTA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "PUNTO_COMA",
  "ENTERO",
  "DECIMAL",
  "RIGHT",
  "LEFT",
  "UP",
  "DOWN",
  "PUSH",
  "FLOOR",
  "CEIL",
  "SYM"
  };
}

