
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mio.cliente.boxworld.compiler.parser;

/** CUP generated class containing symbol constants. */
public class XMLParserSym {
  /* terminals */
  public static final int DIAGONAL = 30;
  public static final int ERRORS = 35;
  public static final int DESCRIPTION = 39;
  public static final int BRICK_COLOR = 21;
  public static final int INTERROGACION = 24;
  public static final int WORLDS = 11;
  public static final int ENTERO = 44;
  public static final int TARGETS = 7;
  public static final int SINTACTICO = 33;
  public static final int BOX_COLOR = 17;
  public static final int TARGET_COLOR = 19;
  public static final int ROWS = 3;
  public static final int CONFIG = 6;
  public static final int IGUAL = 27;
  public static final int LEXICO = 32;
  public static final int COLUMN = 38;
  public static final int TYPE = 12;
  public static final int BOX_ON_TARGET_COLOR = 18;
  public static final int BOARD = 9;
  public static final int VERSION = 26;
  public static final int HALL = 42;
  public static final int SEMANTICO = 34;
  public static final int HALL_COLOR = 22;
  public static final int BRICK = 43;
  public static final int EOF = 0;
  public static final int PLAYER = 5;
  public static final int PALABRA = 45;
  public static final int error = 1;
  public static final int SYM = 31;
  public static final int LINE = 37;
  public static final int MAYOR_QUE = 16;
  public static final int WORLD = 10;
  public static final int ERROR = 36;
  public static final int NAME = 2;
  public static final int LEXEMA = 40;
  public static final int POSY = 14;
  public static final int POSX = 13;
  public static final int COLS = 4;
  public static final int LITERAL = 28;
  public static final int BOXES = 8;
  public static final int ENCODING = 29;
  public static final int HEXADECIMAL = 41;
  public static final int MENOR_QUE = 15;
  public static final int XML = 25;
  public static final int UNDEFINED_COLOR = 20;
  public static final int PLAYER_COLOR = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAME",
  "ROWS",
  "COLS",
  "PLAYER",
  "CONFIG",
  "TARGETS",
  "BOXES",
  "BOARD",
  "WORLD",
  "WORLDS",
  "TYPE",
  "POSX",
  "POSY",
  "MENOR_QUE",
  "MAYOR_QUE",
  "BOX_COLOR",
  "BOX_ON_TARGET_COLOR",
  "TARGET_COLOR",
  "UNDEFINED_COLOR",
  "BRICK_COLOR",
  "HALL_COLOR",
  "PLAYER_COLOR",
  "INTERROGACION",
  "XML",
  "VERSION",
  "IGUAL",
  "LITERAL",
  "ENCODING",
  "DIAGONAL",
  "SYM",
  "LEXICO",
  "SINTACTICO",
  "SEMANTICO",
  "ERRORS",
  "ERROR",
  "LINE",
  "COLUMN",
  "DESCRIPTION",
  "LEXEMA",
  "HEXADECIMAL",
  "HALL",
  "BRICK",
  "ENTERO",
  "PALABRA"
  };
}

