
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mio.server.compiler.parser;

/** CUP generated class containing symbol constants. */
public class JsonParserSym {
  /* terminals */
  public static final int BRICK_COLOR = 21;
  public static final int WORLDS = 10;
  public static final int ENTERO = 39;
  public static final int RESTA = 33;
  public static final int TARGETS = 7;
  public static final int DOS_PUNTOS = 31;
  public static final int CORCHETE_C = 29;
  public static final int BOX_COLOR = 17;
  public static final int TARGET_COLOR = 19;
  public static final int CORCHETE_A = 28;
  public static final int LLAVE_C = 25;
  public static final int FLOOR = 42;
  public static final int LLAVE_A = 24;
  public static final int ROWS = 3;
  public static final int CONFIG = 6;
  public static final int TYPE = 13;
  public static final int BOX_ON_TARGET_COLOR = 18;
  public static final int BOARD = 9;
  public static final int SUMA = 32;
  public static final int HALL = 37;
  public static final int HALL_COLOR = 22;
  public static final int DECIMAL = 40;
  public static final int BRICK = 38;
  public static final int EOF = 0;
  public static final int PLAYER = 5;
  public static final int PALABRA = 41;
  public static final int error = 1;
  public static final int COMILLA = 16;
  public static final int COMA = 30;
  public static final int WORLD = 11;
  public static final int NAME = 2;
  public static final int POSY = 15;
  public static final int POSX = 14;
  public static final int COLS = 4;
  public static final int PARENTESIS_C = 27;
  public static final int PARENTESIS_A = 26;
  public static final int BOXES = 8;
  public static final int HEXADECIMAL = 36;
  public static final int ALL = 12;
  public static final int CEIL = 43;
  public static final int DIVISION = 35;
  public static final int UNDEFINED_COLOR = 20;
  public static final int PLAYER_COLOR = 23;
  public static final int MULTIPLICACION = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAME",
  "ROWS",
  "COLS",
  "PLAYER",
  "CONFIG",
  "TARGETS",
  "BOXES",
  "BOARD",
  "WORLDS",
  "WORLD",
  "ALL",
  "TYPE",
  "POSX",
  "POSY",
  "COMILLA",
  "BOX_COLOR",
  "BOX_ON_TARGET_COLOR",
  "TARGET_COLOR",
  "UNDEFINED_COLOR",
  "BRICK_COLOR",
  "HALL_COLOR",
  "PLAYER_COLOR",
  "LLAVE_A",
  "LLAVE_C",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "COMA",
  "DOS_PUNTOS",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "HEXADECIMAL",
  "HALL",
  "BRICK",
  "ENTERO",
  "DECIMAL",
  "PALABRA",
  "FLOOR",
  "CEIL"
  };
}

